process.env.NEXT_PUBLIC_CONTENTFUL_CONTENT_MANAGEMENT_TOKEN = 'CFPAT-12_ceGnQ5u8rPAaA8GBXQJlZrvcgul_jHtE6QwQDTNY'
process.env.NEXT_PUBLIC_JEST_CONTENT_ID = ''
process.env.NEXT_PUBLIC_JEST_SPACE_ID = ''
